### ISSUE TITLE
Win32 error 0n127 - the specified procedure could not be found

### ISSUE THREAD

**Issue by theguly** [fdiskyou/iris#4]
hello, i'm trying to use latest release of iris on a windbg10 amd64 on windows7 but looks like i'm missing something.

running .load iris windbg says:
The call to LoadLibrary(iris) failed, Win32 error 0n127
    "The specified procedure could not be found."
i think i have the right vc but to be sure i also tried to recompile with no luck, i have the same error.

how can i trace down this issue?

thanks

**Comment by fdiskyou** [comment]
Hi, the minimum supported versions are Windows 8 and Windows Server 2012. Reason being is the API all used is not available in previous Windows versions. I'll add this to the documentation.

**Comment by fdiskyou** [comment]
Documentation has been updated.
